// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentMargin
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocumentMargin.a5a7bd52-f250-4930-83b4-2085f8b9c7de";
        public const string Name = "Editor Info";
        public const string Description = @"Adds a margin to the editor that displays the text length, selection length, and total number of lines in the file. It also shows the encoding of the of the file and let you easily change it.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
