// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DocumentMargin
{
    internal sealed partial class Vsix
    {
        public const string Id = "DocumentMargin.a5a7bd52-f250-4930-83b4-2085f8b9c7de";
        public const string Name = "Document Margin";
        public const string Description = @"Adds encoding and selection information to the bottom editor margin";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
