// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace DocumentMargin
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string DocumentMarginString = "91ef11a2-e68d-4ac8-80be-aefff53f409a";
        public static Guid DocumentMargin = new Guid(DocumentMarginString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int EncodingMenu = 0x0001;
        public const int EncodingMenuGroup = 0x0002;
        public const int EncodingMenuDynamicStart = 0x1001;
    }
}